### ISSUE TITLE
'next' and 'prev' skip a page when using href-option

### ISSUE THREAD

**Issue by gvanderploeg** [botmonster/jquery-bootpag#19]
When clicking the next- or prev-button combined with the use of the custom href-option, the {{number}} in the href will skip a page.
When beginning on page 1, clicking on 'next' will have these effects:
- page 2 in the pager is highlighted as the current (expected)
- but the browser URL will have changed to #page-3 (or ?page=3, whatever actual href-option was configured) (unexpected)

Same goes for the 'prev' button.

Example with debug logging in JS Fiddle: http://jsfiddle.net/SuUZ6/

**Comment by botmonster** [comment]
should work fine since 1.0.6

**Comment by concreto** [comment]
...still had this issue with 1.0.7. Thanks to @gvanderploeg, your idea helped us a lot!

**Comment by signalw** [comment]
I'm also having the same issue, with 1.0.7...

**Comment by Namstel** [comment]
I'm also having this issue with 1.0.7. Thanks for the suggestion @gvanderploeg.

**Comment by mariummalik22** [comment]
I am also facing the same issue on 1.0.7

**Comment by chaitu234kin** [comment]
Hi @gvanderploeg , Can you please let me know the fix you did for the above issue

**Comment by gvanderploeg** [comment]
@chaitu234kin , it's more than 5 years ago... I don't know by heart anymore. But according to [my comment above](https://github.com/botmonster/jquery-bootpag/issues/19#issuecomment-42658874), that workaround did it for me.
