### ISSUE TITLE
It appears twice pagination

### ISSUE THREAD

**Issue by nenadfemic** [botmonster/jquery-bootpag#20]
When in javascript write load ($("#content").load("ok.php?Page=" + num);),
and click on pagination, it appears twice pagination, and should be only one.

![problem](https://f.cloud.github.com/assets/6898640/2368206/718d1c66-a79c-11e3-84c2-6fd36089c504.PNG)
![p3](https://f.cloud.github.com/assets/6898640/2368213/d1484298-a79c-11e3-9db0-676e3bb41057.PNG)

<script type="text/javascript">
                       $(document).ready(function () {

                        $('#pagination-here').bootpag({
                             total: 22,          // total pages
    page: 1,            // default page
    maxVisible: 5,     // visible pagination

                        }).on('page', function(event, num){
                            $("#content").load("ok.php?Page=" + num); // or some ajax content loading...
                    
                         });
                        

});
                         
                    </script>

**Comment by botmonster** [comment]
You are loading same page recursively
